nginx:
  build: images/nginx
  ports:
   - "80:80"
  volumes:
   - ./:/var/www/project-dev
  privileged: true
  command: nginx -g "daemon off;"
  links:
   - php

php:
  build: images/php
  ports:
   - "9000:9000"
  volumes:
   - ./:/var/www/project-dev
  privileged: true
  working_dir: /var/www/project-dev
  command: php-fpm
#  environment:
#    PGSQL_DB_HOST: db
#    PGSQL_DB_PORT: 5432
#    PGSQL_DB_DATABASE: project_dev
#    PGSQL_DB_USERNAME: postgres
#    PGSQL_DB_PASSWORD: 123456
  user: www-data
  links:
   - db

db:
  build: images/postgresql
  restart: always
  ports:
   - "54321:5432"
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: 123456
  user: postgres

adminer:
  image: adminer
  restart: always
  ports:
  - "54320:8080"
  links:
  - db

#composer:
#  image: prooph/composer:7.1
#  volumes:
#   - ../:/var/www/project_dev
#  working_dir: /var/www/project_dev
#  command: composer install