nginx:
  build: images/nginx
  ports:
    - "80:80"
  volumes:
    - ./:/var/www/project-dev
  privileged: true
  command: nginx -g "daemon off;"
  links:
    - php

php:
  build: images/php
#  ports:
#    - "9000:9000"
  volumes:
    - ./:/var/www/project-dev
  privileged: true
  working_dir: /var/www/project-dev
  command: php-fpm
#  environment:
#    PGSQL_DB_HOST: db
#    PGSQL_DB_PORT: 5432
#    PGSQL_DB_DATABASE: project_dev
#    PGSQL_DB_USERNAME: postgres
#    PGSQL_DB_PASSWORD: 123456
  user: www-data
  links:
    - postgresql
    - mysql

postgresql:
  build: images/postgresql
  restart: always
  ports:
    - "5433:5432"
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: 123456
  user: postgres

mysql:
  build: mysql
#  ports:
#    - 3307:3306
  volumes:
    - ../mysqldata:/var/lib/mysql
  privileged: true
  working_dir: /var/scripts
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: 123456

adminer:
  image: adminer
  restart: always
  ports:
    - "9999:8080"
  links:
    - postgresql
    - mysql

#composer:
#  image: prooph/composer:7.1
#  volumes:
#   - ../:/var/www/project_dev
#  working_dir: /var/www/project_dev
#  command: composer install